spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/bookstore?useUnicode=yes&characterEncoding=UTF-8
    username: root

  jpa:
    database-platform: MySQL5InnoDB
    hibernate:
      ddl-auto: none
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework.web: DEBUG

  thymeleaf:
    mode: LEGACYHTML5
    cache: true